---
name: run-help
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  help-linux:
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: 'x86_64'
            runner: 'ubuntu-latest'
            suffix: ''
          - arch: 'arm64'
            runner: 'ubuntu-24.04-arm'
            suffix: '-arm64'
    name: help-linux-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: wait for build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: linux-${{ matrix.config.arch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: linux${{ matrix.config.suffix }}
      - name: Extract artifact
        run: |
          chmod +x lmms-*.AppImage
          ./lmms-*.AppImage --appimage-extract
      - name: Display help
        run: |
          cd squashfs-root/
          ./AppRun --help | grep "Usage: lmms"
  help-macos:
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: 'x86_64'
            runner: 'macos-latest'
          - arch: 'arm64'
            runner: 'macos-latest'
    name: help-macos-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: wait for build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: macos-${{ matrix.config.arch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: macos-${{ matrix.config.arch }}
      - name: Mount the DMG
        run: |
          hdiutil attach lmms-*.dmg -mountpoint ~/tmpvolume
          cp -R ~/tmpvolume/LMMS.app /tmp/
      - name: Display help
        run: |
          /tmp/LMMS.app/Contents/MacOS/lmms --help | grep "Usage: lmms"
